model_num_classes = 7
model = dict(
    type='DiffusionDenoiserModel',
    num_classes=3,
    num_timesteps=100,
    base_channels=64,
    channel_mult=(1, 2, 4, 8),
    num_res_blocks=1,
    attn_resolutions=(8, ),
    dropout=0.1,
    cond_type='crossattn',
    cond_channels=3,
    cond_base_channels=64,
    cond_encoder_type='pretrained',
    pretrained_cond_cfg=dict(
        backbone_type='resnet50',
        pretrained='open-mmlab://resnet50_v1c',
        freeze_stages=1,
        out_channels=[64, 128, 256, 512]),
    transition_type='absorbing',
    beta_schedule='cosine',
    loss_type='hybrid',
    hybrid_lambda=0.01)
dataset_type = 'PseudoLabelDiffusionDataset'
data_root = 'data/OEM_v2_Building'
dataset_num_classes = 3
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375])
crop_size = (512, 512)
data = dict(
    samples_per_gpu=1,
    workers_per_gpu=4,
    train=dict(
        type='PseudoLabelDiffusionDataset',
        data_root='data/OEM_v2_Building',
        img_dir='images',
        ann_dir='labels',
        pseudo_label_dir='pseudolabels',
        split_file='train.txt',
        num_classes=3,
        crop_size=(384, 384),
        img_suffix='.tif',
        label_suffix='.tif',
        img_norm_cfg=dict(
            mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375]),
        is_train=True),
    val=dict(
        type='PseudoLabelDiffusionDataset',
        data_root='data/OEM_v2_Building',
        img_dir='images',
        ann_dir='labels',
        pseudo_label_dir='pseudolabels',
        split_file='val.txt',
        num_classes=3,
        crop_size=(384, 384),
        img_suffix='.tif',
        label_suffix='.tif',
        img_norm_cfg=dict(
            mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375]),
        is_train=False),
    test=dict(
        type='PseudoLabelDiffusionDataset',
        data_root='data/OEM_v2_Building',
        img_dir='images',
        ann_dir='labels',
        pseudo_label_dir='pseudolabels',
        split_file='test.txt',
        num_classes=3,
        crop_size=(384, 384),
        img_suffix='.tif',
        label_suffix='.tif',
        img_norm_cfg=dict(
            mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375]),
        is_train=False))
seed = 42
cudnn_benchmark = True
log_dir = 'work_dirs'
optimizer = dict(type='AdamW', lr=5e-05, betas=(0.9, 0.999), weight_decay=0.01)
lr_scheduler = dict(
    type='cosine', warmup_iters=5000, warmup_ratio=1e-06, min_lr=1e-06)
max_iters = 100000
checkpoint_interval = 5000
eval_interval = 1000
log_interval = 100
use_ema = True
ema_decay = 0.9999
